import React, { useState, useEffect, useRef } from 'react';
import LiveMap from '../components/map/LiveMap';
import DestinationInput from '../components/navigation/DestinationInput';
import HazardAlert from '../components/hazards/HazardAlert';
import RouteChangedNotification from '../components/hazards/RouteChangedNotification';
import EmergencyPanel from '../components/emergency/EmergencyPanel';
import useLocation from '../hooks/useLocation';
import useHazards from '../hooks/useHazards';
import routeService from '../services/routeService';
import cacheService from '../services/cacheService';
import { useAuth } from '../context/AuthContext';
import {
  Navigation,
  Play,
  Square,
  ShieldAlert,
  LogOut,
  Compass,
  Volume2,
  VolumeX,
  MapPin,
  RefreshCw,
  AlertCircle,
  AlertTriangle,
  Camera
} from 'lucide-react';
import LiveCameraSidePanel from '../components/camera/LiveCameraSidePanel';
import DriverHazardReportModal from '../components/hazards/DriverHazardReportModal';

export const UserPanelPage = () => {
  const { user, logout } = useAuth();

  // Real GPS Geolocation Hook (Never hardcoded or fake)
  const {
    currentLocation,
    error: locationError,
    permissionDenied,
    isLocating,
    requestLocation
  } = useLocation();

  const { hazards, activeAlert, setActiveAlert } = useHazards();

  // Destination State (Starting point is ALWAYS the user's real GPS currentLocation)
  const [destination, setDestination] = useState(null);

  const [routeData, setRouteData] = useState(null);
  const [isNavigating, setIsNavigating] = useState(false);
  const [vehiclePosition, setVehiclePosition] = useState(null);
  const [vehicleSpeed, setVehicleSpeed] = useState(0);
  const [remainingDistance, setRemainingDistance] = useState(0);
  const [remainingTime, setRemainingTime] = useState(0);

  // Reroute notification state
  const [showReroutePrompt, setShowReroutePrompt] = useState(false);
  const [routeChangeReason, setRouteChangeReason] = useState('');

  // Emergency panel
  const [emergencyOpen, setEmergencyOpen] = useState(false);

  // Driver Crowdsourced Hazard Reporting modal
  const [reportHazardOpen, setReportHazardOpen] = useState(false);

  // Listen to cross-component report trigger (e.g. Navbar)
  useEffect(() => {
    const handleOpen = () => setReportHazardOpen(true);
    window.addEventListener('open-driver-hazard-report', handleOpen);
    return () => window.removeEventListener('open-driver-hazard-report', handleOpen);
  }, []);

  // Camera Side Panel state (Docked adjacent beside the map, increased size)
  const [cameraOpen, setCameraOpen] = useState(true);
  const [cameraExpanded, setCameraExpanded] = useState(false);

  // Voice announcements
  const [voiceMuted, setVoiceMuted] = useState(false);

  // Section 13: Handle Driver Popups generated by Camera Detection Filter
  const handleDriverAlert = (alert) => {
    if (!alert) return;
    setActiveAlert({
      name: alert.title,
      type: alert.category,
      severity: alert.category === 'flood' || alert.category === 'fire' ? 'CRITICAL' : 'HIGH',
      source: 'AI Camera',
      description: alert.detailsText,
      distance: alert.distance_m ? Math.round(alert.distance_m) : 6,
      distanceText: alert.distance_m ? `~${Math.round(alert.distance_m)} m` : 'Ahead',
      depth_cm: alert.depth_cm,
      recommendation: alert.category === 'pothole'
        ? 'Steer lateral offset to avoid deep cavity.'
        : (alert.category === 'pedestrian' ? 'Slow down immediately, pedestrian crossing.' : 'Hazard detected on active driving path.')
    });
    speak(alert.title.replace('⚠', '').trim());
  };

  const speak = (text) => {
    if (voiceMuted || !('speechSynthesis' in window)) return;
    try {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 1.05;
      window.speechSynthesis.speak(utterance);
    } catch {
      // Audio fallback
    }
  };

  // Calculate distance between two lat/lng points using Haversine formula
  const calculateDistanceKm = (lat1, lon1, lat2, lon2) => {
    const R = 6371; // Earth radius in km
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
      Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return +(R * c).toFixed(1);
  };

  // Plan safe route whenever destination, hazards, or user GPS location updates
  useEffect(() => {
    if (!currentLocation || !destination) return;

    const planRoute = async () => {
      const res = await routeService.planSafeRoute(currentLocation, destination, hazards);
      if (!res) return;
      setRouteData(res);

      const dist = res.primaryRoute?.distance_km || calculateDistanceKm(currentLocation.lat, currentLocation.lng, destination.lat, destination.lng);
      setRemainingDistance(dist);
      setRemainingTime(res.primaryRoute?.duration_minutes || Math.max(2, Math.round(dist * 1.8)));

      if (res.routeChanged && res.isShifted) {
        setRouteChangeReason(res.reasons[0] || 'Hazard detected on primary shortest path.');
        setShowReroutePrompt(true);
        speak('Hazard detected on route. Automatically shifted to shortest bypass path.');

        if (res.hazardOnRoute) {
          const h = res.hazardOnRoute;
          const hLat = h.latitude !== undefined ? h.latitude : h.lat;
          const hLng = h.longitude !== undefined ? h.longitude : h.lng;
          const distKm = calculateDistanceKm(currentLocation.lat, currentLocation.lng, hLat, hLng);
          setActiveAlert({
            name: `${h.name || h.type} detected ahead`,
            type: h.type,
            severity: h.severity || 'HIGH',
            source: h.source || 'Admin',
            description: h.description || `${h.name || 'Hazard'} on active route corridor`,
            distance: Math.round(distKm * 1000),
            distanceText: `${distKm} km`,
            recommendation: 'Hazard directly impacts shortest path. Automatically shifted to shortest bypass path.'
          });
        }
      } else {
        setShowReroutePrompt(false);
      }
    };

    planRoute();
  }, [currentLocation?.lat, currentLocation?.lng, destination, hazards]);

  // Handle Shift: Confirms staying on the shortest bypass path
  const handleShiftRoute = () => {
    setShowReroutePrompt(false);
    if (routeData?.bypassRoute) {
      setRouteData(prev => ({
        ...prev,
        primaryRoute: prev.bypassRoute,
        isShifted: true,
        userChoseOriginal: false
      }));
      setRemainingDistance(routeData.bypassRoute.distance_km);
      setRemainingTime(routeData.bypassRoute.duration_minutes);
    }
    speak('Shortest bypass route confirmed.');
  };

  // Handle Continue: Overrides shift and returns to the original shortest path
  const handleContinueOriginal = () => {
    setShowReroutePrompt(false);
    if (routeData?.shortestRoute) {
      setRouteData(prev => ({
        ...prev,
        primaryRoute: prev.shortestRoute,
        isShifted: false,
        userChoseOriginal: true
      }));
      setRemainingDistance(routeData.shortestRoute.distance_km);
      setRemainingTime(routeData.shortestRoute.duration_minutes);
    }
    speak('Continuing on original route. Please drive with caution.');
  };

  // Real-time GPS location updates during navigation
  useEffect(() => {
    if (isNavigating && currentLocation) {
      setVehiclePosition({ lat: currentLocation.lat, lng: currentLocation.lng });
      setVehicleSpeed(currentLocation.speed > 0 ? currentLocation.speed : 48);

      if (destination) {
        const dist = calculateDistanceKm(currentLocation.lat, currentLocation.lng, destination.lat, destination.lng);
        setRemainingDistance(dist);
        setRemainingTime(Math.max(1, Math.round(dist * 1.8)));
      }
    }
  }, [currentLocation, isNavigating, destination]);

  // Handle Start / Stop Navigation
  const handleToggleNavigation = () => {
    if (!destination) {
      speak('Please enter a destination to start navigation.');
      return;
    }

    if (isNavigating) {
      if (destination) {
        cacheService.saveTripToMemory({
          destination: destination.name,
          distanceKm: remainingDistance || 4.8,
          durationMin: Math.max(1, Math.round(remainingTime || 14)),
          hazardsAvoided: routeData?.routeChanged ? 1 : 0,
          safetyRating: routeData?.routeChanged ? 'A+ (Safe Detour)' : 'A (Optimal Path)'
        });
      }
      setIsNavigating(false);
      setVehicleSpeed(0);
      setVehiclePosition(null);
      speak('Navigation completed and saved to drive memory.');
    } else {
      setIsNavigating(true);
      setVehiclePosition({ lat: currentLocation.lat, lng: currentLocation.lng });
      setVehicleSpeed(currentLocation.speed > 0 ? currentLocation.speed : 52);
      speak(`Starting navigation to ${destination.name || 'destination'}. Starting from your current location.`);
    }
  };

  const handleHazardClick = (hazard) => {
    setActiveAlert({
      name: hazard.name || hazard.type,
      type: hazard.type,
      distance: hazard.distance || 450,
      distanceText: hazard.distanceText || 'Nearby',
      severity: hazard.severity || 'HIGH',
      source: hazard.source || 'Admin',
      description: hazard.description || (hazard.type?.includes('pothole') ? 'Deep road surface cavity.' : 'Active hazard condition.'),
      recommendation: hazard.type?.includes('pothole')
        ? 'Deep pothole cavity ahead. Steer 0.5m lateral offset.'
        : 'Severe hazard reported. Proceed via elevated bypass.'
    });
  };

  // =========================================================================
  // LOCATION PERMISSION DENIED OR UNAVAILABLE STATE
  // =========================================================================
  if (permissionDenied || (!currentLocation && locationError)) {
    return (
      <div
        style={{
          minHeight: 'calc(100vh - 80px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '24px',
          background: '#f8fafc'
        }}
      >
        <div
          className="glass-panel"
          style={{
            maxWidth: '480px',
            width: '100%',
            padding: '36px 28px',
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: '18px',
            border: '2px solid #ef4444',
            boxShadow: '0 20px 40px rgba(239, 68, 68, 0.15)'
          }}
        >
          <div
            style={{
              background: '#fee2e2',
              color: '#dc2626',
              width: '64px',
              height: '64px',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}
          >
            <MapPin size={32} />
          </div>

          <h2 style={{ fontSize: '1.25rem', color: '#0f172a', fontWeight: 800, margin: 0 }}>
            Location Access Required
          </h2>

          <p style={{ fontSize: '0.95rem', color: '#475569', lineHeight: 1.6, whiteSpace: 'pre-line', margin: 0 }}>
            Location access is required for navigation.
            Please enable location permission.
          </p>

          <button
            onClick={requestLocation}
            className="btn btn-primary"
            style={{
              padding: '12px 24px',
              fontSize: '0.9rem',
              fontWeight: 800,
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              marginTop: '8px'
            }}
          >
            <RefreshCw size={16} /> Enable Location Permission / Retry
          </button>
        </div>
      </div>
    );
  }

  // =========================================================================
  // ACQUIRING GPS LOCATION STATE
  // =========================================================================
  if (isLocating && !currentLocation) {
    return (
      <div
        style={{
          minHeight: 'calc(100vh - 80px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '24px',
          background: '#f8fafc'
        }}
      >
        <div
          className="glass-panel"
          style={{
            maxWidth: '380px',
            width: '100%',
            padding: '32px 24px',
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: '14px'
          }}
        >
          <div className="animate-spin" style={{ color: '#0284c7' }}>
            <Compass size={40} />
          </div>
          <h3 style={{ fontSize: '1.05rem', color: '#0f172a', fontWeight: 800, margin: 0 }}>
            Acquiring Current GPS Location
          </h3>
          <p style={{ fontSize: '0.82rem', color: '#64748b', margin: 0 }}>
            Requesting browser GPS satellites for vehicle anchor...
          </p>
        </div>
      </div>
    );
  }

  // =========================================================================
  // MAIN LIVE MAP USER PANEL
  // =========================================================================
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'row',
        height: 'calc(100vh - 72px)',
        width: '100%',
        maxWidth: '100vw',
        position: 'relative',
        overflow: 'hidden',
        background: '#090d16'
      }}
    >
      {/* Primary Column: Live Map Canvas with Floating HUD & Navigation Controls */}
      <div
        style={{
          flex: 1,
          height: '100%',
          position: 'relative',
          minWidth: 0,
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden'
        }}
      >
        {/* Top Floating Bar */}
        <header
          style={{
            position: 'absolute',
            top: '16px',
            left: '16px',
            right: '16px',
            zIndex: 600,
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            pointerEvents: 'none'
          }}
        >
          {/* Left: Destination Input */}
          <div style={{ pointerEvents: 'auto', display: 'flex', alignItems: 'center', gap: '12px' }}>
            {!isNavigating && (
              <DestinationInput
                onSelectDestination={(dest) => setDestination(dest)}
                selectedDestination={destination}
                currentLocation={currentLocation}
                disabled={isNavigating}
              />
            )}
          </div>

          {/* Right: Quick Controls */}
          <div style={{ pointerEvents: 'auto', display: 'flex', alignItems: 'center', gap: '8px' }}>
            {/* Quick Driver Hazard Crowdsource Report Button */}
            <button
              onClick={() => setReportHazardOpen(true)}
              className="btn"
              style={{
                background: 'linear-gradient(135deg, #ea580c, #c2410c)',
                color: '#ffffff',
                border: '1px solid #ea580c',
                boxShadow: '0 4px 16px rgba(234, 88, 12, 0.35)',
                padding: '8px 14px',
                fontSize: '0.84rem',
                fontWeight: 800,
                borderRadius: '10px',
                display: 'flex',
                alignItems: 'center',
                gap: '7px',
                cursor: 'pointer',
                transition: 'all 0.2s ease'
              }}
              title="Report Hazard & Snap/Upload Road Photo with GPS"
            >
              <AlertTriangle size={16} color="#ffffff" />
              <span>Report Hazard</span>
            </button>

            {/* Camera Toggle Button: Docks / Undocks Live Vision Beside Map */}
            <button
              onClick={() => setCameraOpen(!cameraOpen)}
              className="btn btn-secondary"
              style={{
                background: cameraOpen ? '#0284c7' : 'rgba(255, 255, 255, 0.92)',
                color: cameraOpen ? '#ffffff' : '#0f172a',
                backdropFilter: 'blur(12px)',
                WebkitBackdropFilter: 'blur(12px)',
                border: cameraOpen ? '1px solid #0284c7' : '1px solid rgba(255, 255, 255, 0.8)',
                boxShadow: cameraOpen ? '0 4px 16px rgba(2, 132, 199, 0.35)' : '0 4px 16px rgba(15, 23, 42, 0.08)',
                padding: '8px 14px',
                fontSize: '0.84rem',
                fontWeight: 800,
                borderRadius: '10px',
                display: 'flex',
                alignItems: 'center',
                gap: '7px',
                cursor: 'pointer',
                transition: 'all 0.2s ease'
              }}
              title={cameraOpen ? "Hide Live Camera Feed" : "Open Live Camera Beside Map"}
            >
              <Camera size={16} color={cameraOpen ? "#ffffff" : "#0284c7"} />
              <span>{cameraOpen ? 'Camera Active' : 'Camera'}</span>
              <span
                style={{
                  width: '7px',
                  height: '7px',
                  borderRadius: '50%',
                  background: cameraOpen ? '#4ade80' : '#94a3b8',
                  boxShadow: cameraOpen ? '0 0 6px #4ade80' : 'none',
                  display: 'inline-block'
                }}
              />
            </button>

            {/* Emergency SOS button */}
            <button
              onClick={() => setEmergencyOpen(true)}
              className="btn btn-secondary"
              style={{
                background: 'rgba(254, 242, 242, 0.95)',
                border: '1px solid #fca5a5',
                boxShadow: '0 4px 16px rgba(239, 68, 68, 0.12)',
                padding: '8px 12px',
                fontSize: '0.84rem',
                fontWeight: 800,
                borderRadius: '10px',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                color: '#dc2626'
              }}
              title="Emergency SOS & Medical Help Centers"
            >
              <ShieldAlert size={16} color="#dc2626" />
              <span>SOS</span>
            </button>

            <button
              onClick={() => setVoiceMuted(!voiceMuted)}
              className="btn btn-secondary"
              style={{
                background: 'rgba(255, 255, 255, 0.82)',
                backdropFilter: 'blur(12px)',
                WebkitBackdropFilter: 'blur(12px)',
                border: '1px solid rgba(255, 255, 255, 0.6)',
                boxShadow: '0 4px 16px rgba(15, 23, 42, 0.08)',
                padding: '8px 12px',
                fontSize: '0.8rem',
                borderRadius: '10px'
              }}
              title={voiceMuted ? "Enable Voice" : "Mute Voice"}
            >
              {voiceMuted ? <VolumeX size={16} color="#64748b" /> : <Volume2 size={16} color="#0284c7" />}
            </button>
          </div>
        </header>

        {/* Main Full-Bleed Map Canvas */}
        <div style={{ flex: 1, width: '100%', height: '100%', position: 'relative' }}>
          <LiveMap
            currentLocation={currentLocation}
            destination={destination}
            routeData={routeData}
            hazards={hazards}
            onHazardClick={handleHazardClick}
            vehiclePosition={vehiclePosition}
            isNavigating={isNavigating}
          />
        </div>

        {/* Floating Bottom Navigation Bar */}
        <div
          style={{
            position: 'absolute',
            bottom: '24px',
            left: '50%',
            transform: 'translateX(-50%)',
            zIndex: 600,
            maxWidth: '520px',
            width: '92%',
            background: 'rgba(255, 255, 255, 0.96)',
            backdropFilter: 'blur(12px)',
            borderRadius: '16px',
            border: '1px solid #cbd5e1',
            boxShadow: '0 12px 32px rgba(15, 23, 42, 0.15)',
            padding: '16px 20px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '16px'
          }}
        >
          {isNavigating ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px', flex: 1 }}>
              <div
                style={{
                  background: '#0284c7',
                  color: '#fff',
                  width: '42px',
                  height: '42px',
                  borderRadius: '10px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  flexShrink: 0
                }}
              >
                <Compass size={24} />
              </div>
              <div>
                <div style={{ fontSize: '0.7rem', color: '#64748b', fontWeight: 800, textTransform: 'uppercase' }}>
                  CURRENT ROUTE: {destination?.name || 'Destination'}
                </div>
                <div style={{ fontSize: '1.15rem', fontWeight: 900, color: '#0f172a' }}>
                  {vehicleSpeed} <span style={{ fontSize: '0.78rem', color: '#64748b' }}>km/h</span> • {remainingDistance} km
                </div>
                <div style={{ fontSize: '0.74rem', color: '#059669', fontWeight: 700 }}>
                  {routeData?.routeChanged ? 'Autonomous Detour Active' : 'Optimal Path • Monitored Safe'}
                </div>
              </div>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '2px', flex: 1 }}>
              <span style={{ fontSize: '0.72rem', color: '#64748b', fontWeight: 700, textTransform: 'uppercase' }}>
                {destination ? 'TARGET DESTINATION' : 'STARTING POINT: YOUR CURRENT LOCATION'}
              </span>
              <span style={{ fontSize: '0.98rem', fontWeight: 800, color: '#0f172a' }}>
                {destination ? destination.name : 'Enter Destination to Start'}
              </span>
              {destination && (
                <span style={{ fontSize: '0.74rem', color: '#0284c7', fontWeight: 600 }}>
                  ETA ~{remainingTime || routeData?.newETA || 25} mins • Distance {remainingDistance} km
                </span>
              )}
            </div>
          )}

          {/* Start / Stop Navigation Button */}
          <button
            onClick={handleToggleNavigation}
            style={{
              background: isNavigating ? '#dc2626' : (destination ? '#0284c7' : '#94a3b8'),
              color: '#ffffff',
              border: 'none',
              borderRadius: '12px',
              padding: '12px 24px',
              fontSize: '0.95rem',
              fontWeight: 800,
              cursor: destination ? 'pointer' : 'not-allowed',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              boxShadow: isNavigating ? '0 4px 14px rgba(220, 38, 38, 0.4)' : '0 4px 14px rgba(2, 132, 199, 0.4)',
              flexShrink: 0
            }}
            disabled={!destination && !isNavigating}
          >
            {isNavigating ? (
              <>
                <Square size={18} /> Stop Navigation
              </>
            ) : (
              <>
                <Play size={18} /> Start Navigation
              </>
            )}
          </button>
        </div>

        {/* Popups & Notifications */}
        {activeAlert && (
          <HazardAlert
            alert={activeAlert}
            onClose={() => setActiveAlert(null)}
            onViewRoute={() => setActiveAlert(null)}
          />
        )}

        {showReroutePrompt && (
          <RouteChangedNotification
            reason={routeChangeReason}
            oldETA={routeData?.originalETA || remainingTime}
            newETA={routeData?.newETA || remainingTime}
            oldDistanceKm={routeData?.originalDistanceKm || remainingDistance}
            newDistanceKm={routeData?.bypassRoute?.distance_km || remainingDistance}
            onShift={handleShiftRoute}
            onContinue={handleContinueOriginal}
            onClose={() => setShowReroutePrompt(false)}
          />
        )}

        <EmergencyPanel
          isOpen={emergencyOpen}
          onClose={() => setEmergencyOpen(false)}
          currentLocation={currentLocation}
        />

        <DriverHazardReportModal
          isOpen={reportHazardOpen}
          onClose={() => setReportHazardOpen(false)}
          currentLocation={currentLocation}
        />
      </div>

      {/* Adjacent Docked Live Camera Panel (Directly beside the map, increased size) */}
      {cameraOpen && (
        <aside
          style={{
            width: cameraExpanded ? '640px' : '520px',
            maxWidth: '52vw',
            minWidth: '380px',
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            borderLeft: '2px solid rgba(255, 255, 255, 0.1)',
            boxShadow: '-8px 0 28px rgba(0, 0, 0, 0.35)',
            zIndex: 650,
            position: 'relative',
            transition: 'width 0.25s cubic-bezier(0.4, 0, 0.2, 1)'
          }}
        >
          <LiveCameraSidePanel
            currentLocation={currentLocation}
            onDriverAlert={handleDriverAlert}
            onClose={() => setCameraOpen(false)}
            isExpanded={cameraExpanded}
            onToggleExpand={() => {
              setCameraExpanded(prev => !prev);
              setTimeout(() => {
                window.dispatchEvent(new Event('resize'));
              }, 120);
            }}
          />
        </aside>
      )}
    </div>
  );

};

export default UserPanelPage;
